Revert the removal of an option to block autoplay
bromite/bromite pull request #802
Opened 2020-11-07 22:03 UTC by uazo

fix #791

2020-11-07 23:05 UTC, csagan5 requested changes
Please submit the patch without removing anything from it (`index` lines etc); it is currently corrupt.

```
error: cannot apply binary patch to 'components/browser_ui/site_settings/android/java/res/drawable-hdpi/settings_autoplay.png' without full index line
error: components/browser_ui/site_settings/android/java/res/drawable-hdpi/settings_autoplay.png: patch does not apply
error: cannot apply binary patch to 'components/browser_ui/site_settings/android/java/res/drawable-hdpi/settings_media.png' without full index line
error: components/browser_ui/site_settings/android/java/res/drawable-hdpi/settings_media.png: patch does not apply
error: cannot apply binary patch to 'components/browser_ui/site_settings/android/java/res/drawable-mdpi/settings_autoplay.png' without full index line
error: components/browser_ui/site_settings/android/java/res/drawable-mdpi/settings_autoplay.png: patch does not apply
error: cannot apply binary patch to 'components/browser_ui/site_settings/android/java/res/drawable-mdpi/settings_media.png' without full index line
error: components/browser_ui/site_settings/android/java/res/drawable-mdpi/settings_media.png: patch does not apply
error: cannot apply binary patch to 'components/browser_ui/site_settings/android/java/res/drawable-xhdpi/settings_autoplay.png' without full index line
error: components/browser_ui/site_settings/android/java/res/drawable-xhdpi/settings_autoplay.png: patch does not apply
error: cannot apply binary patch to 'components/browser_ui/site_settings/android/java/res/drawable-xhdpi/settings_media.png' without full index line
error: components/browser_ui/site_settings/android/java/res/drawable-xhdpi/settings_media.png: patch does not apply
error: cannot apply binary patch to 'components/browser_ui/site_settings/android/java/res/drawable-xxhdpi/settings_autoplay.png' without full index line
error: components/browser_ui/site_settings/android/java/res/drawable-xxhdpi/settings_autoplay.png: patch does not apply
error: cannot apply binary patch to 'components/browser_ui/site_settings/android/java/res/drawable-xxhdpi/settings_media.png' without full index line
error: components/browser_ui/site_settings/android/java/res/drawable-xxhdpi/settings_media.png: patch does not apply
error: cannot apply binary patch to 'components/browser_ui/site_settings/android/java/res/drawable-xxxhdpi/settings_autoplay.png' without full index line
error: components/browser_ui/site_settings/android/java/res/drawable-xxxhdpi/settings_autoplay.png: patch does not apply
error: cannot apply binary patch to 'components/browser_ui/site_settings/android/java/res/drawable-xxxhdpi/settings_media.png' without full index line
error: components/browser_ui/site_settings/android/java/res/drawable-xxxhdpi/settings_media.png: patch does not apply
```

2020-11-08 01:10 UTC, csagan5 commented on build/bromite_patches_list.txt
> +Revert-removal-option-to-block-autoplay.patch
I made a commit to fix this.

2020-11-08 01:11 UTC, csagan5 commented
@uazo I have also fixed the corrupt patch; please see my commit.

2020-11-08 07:47 UTC, csagan5 approved these changes
There are a few things to fix, but I will fix them before next release myself:
* the `Media` menu seems to be useless, since it points to the same site settings; I might have misunderstood its importance; I will remove it
* default should be `Autoplay disabled`
* it does not show in the individual site settings (if I cannot fix this for this release, I will leave it to you on next release)

2020-11-08 07:47 UTC, merged

2020-11-08 09:18 UTC, uazo commented on build/bromite_patches_list.txt
> +Revert-removal-option-to-block-autoplay.patch
sorry, translation error, in Italian "can" is "puoi" (if you want), simply I was trusting that you was be pleased.
no problem, next time I'll put it on the bottom.

2020-11-08 09:21 UTC, uazo commented
>- default should be Autoplay disabled
> - it does not show in the page info site settings (if I cannot fix this for this release, I will leave it to you on next release)

yes, I thought we discussed it first
I would also say that we should understand if "media engamenent" is useful for privacy

2020-11-08 09:26 UTC, csagan5 commented
I do not follow you.

I have fixed all of the above, the only issue left is that it does not show on the page info when clicking on the URL bar icon. I am trying to fix it before release.

2020-11-08 09:44 UTC, uazo commented
> I do not follow you.

I'm referring to "some obscure engagement score"

2020-11-08 09:46 UTC, csagan5 commented
> I'm referring to "some obscure engagement score"

Ok, but we are [discussing that in the issue](https://github.com/bromite/bromite/issues/791#issuecomment-723547781) not here.